language: node_js
node_js:
    - 10
before_install:
    - 'npm install -g npm@latest'
env:
    global:
        - ENCRYPTION_LABEL: "823030436da4"
        - COMMIT_AUTHOR_EMAIL: "towerofnix@gmail.com"
jobs:
    include:
        - stage: test
          script: npm run test
        - stage: deploy docs
          script: bash ./deploy.sh
